name: Verify Server start

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  check-health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start server
        run: npm start &

      - name: Check server health with retry
        run: |
          echo "Checking server health with retry logic..."
          for i in {1..5}; do
            echo "Attempt $i/5..."
            if curl --fail --silent --max-time 5 http://localhost:9090/health; then
              echo "✅ Server is healthy!"
              exit 0
            else
              echo "❌ Health check failed on attempt $i"
              if [ $i -lt 5 ]; then
                sleep_time=$((2 ** i))
                echo "Waiting ${sleep_time}s before retry..."
                sleep $sleep_time
              fi
            fi
          done
          echo "❌ Server failed to start after 5 attempts"
          echo "Debugging info:"
          echo "Checking if server process is running..."
          ps aux | grep -E "(node|npm)" | grep -v grep || echo "No node processes found"
          echo "Checking what's listening on port 9090..."
          netstat -tlnp 2>/dev/null | grep :9090 || echo "Nothing listening on port 9090"
          exit 1
